#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT

ctags --tag-relative=yes -R -f "$dir/$$.tags" \
    --fields=+aimlS \
    --languages=php \
    --exclude=composer.phar \
    --exclude=*Test.php \
    --exclude=*phpunit* \
    --exclude=vendor/bin \
    --exclude=vendor/friendsofphp/php-cs-fixer \
    --exclude=vendor/phpstan \
    --exclude=var \
    --exclude=vendor/vimeo \
    --exclude=vendor/infection \
    --exclude=vendor/slam/phpstan-extensions \
    --exclude=vendor/povils/phpmnd \
    --exclude="\.git" \
    --regex-PHP='/(public\s+|static\s+|protected\s+|private\s+)\$([^     =]+)/\2/p/' \
    --PHP-kinds=+cdfint-av > ctag_errors.log 2>&1
    #--PHP-kinds=+cdfi-v > ctag_errors.log 2>&1

mv "$dir/$$.tags" "$dir/tags"
